"$schema" = "https://conductor.build/schemas/settings.repo.schema.json"

[scripts]
run_mode = "nonconcurrent"

[scripts.run.device]
available_in = [ "local" ]
command = "scripts/run-device.sh"
default = true
icon = "smartphone"

[scripts.run.install-mac]
available_in = [ "local" ]
command = "scripts/install-mac.sh"
icon = "package"
